sys = require 'sys'
fs = require 'fs'
exec = require('child_process').exec
spawn = require('child_process').spawn

option '-l', '--level [LEVEL]', 'Specifies closure compiler’s compliation level (whitespace, simple, advanced)'

LEVELS =
  whitespace: 'WHITESPACE_ONLY'
  simple: 'SIMPLE_OPTIMIZATIONS'
  advanced: 'ADVANCED_OPTIMIZATIONS'

task 'js:compile', 'compile javascript using google’s closure compiler', (options) ->
  level = LEVELS[options.level || 'simple']
  
  inputFile = 'stylesheets/application.js'
  outputFile = 'stylesheets/application.min.js'
  
  clojure = exec "java -jar dist/compiler.jar --compilation_level #{level} --js #{inputFile} --js_output_file #{outputFile}", (error, stdout, stderr) ->
    puts stderr, stdout

task 'watch', 'watches and compiles coffee', ->
  puts "Spawning coffee watcher"
  coffee = spawn 'coffee', ['-cwl', '-o', 'javascripts', 'coffeescripts']

  puts "Spawning sass watcher"
  sass   = spawn 'sass',   ['--watch', 'sass:stylesheets']
  
  [coffee, sass].forEach (child) ->
      child.stdout.on 'data', (data) ->
        sys.print data
        exec "growlnotify -m \"#{data}\" -t \"Cakefile\""
      child.stderr.on 'data', (data) ->
        sys.print data
        exec "growlnotify -m \"#{data}\" -t \"Cakefile\""